routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes([
    'register' => false
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'role:Divisi Akuntansi|supervisor'])->group(function() {
    Route::resource('financial_statements', 'FinancialStatement\FinancialStatementController')
        ->only(['index', 'show']);
    Route::get('financial_statements/general_entries/export/excel', 'FinancialStatement\FinancialStatementController@exportGeneralEntriesExcel')->name('financial_statements.general_entries.export.excel');
    Route::get('financial_statements/balance_sheet/export/excel', 'FinancialStatement\FinancialStatementController@exportBalanceSheetExcel')->name('financial_statements.balance_sheet.export.excel');
    Route::get('financial_statements/income_statement/export/excel', 'FinancialStatement\FinancialStatementController@exportIncomeStatementExcel')->name('financial_statements.income_statement.export.excel');
});

Route::resource('accounts', 'Account\AccountController')->middleware(['auth', 'role:Divisi Akuntansi|supervisor']);

Route::middleware(['auth', 'role:Divisi Akuntansi|Divisi Piutang|supervisor'])->prefix('receivables')->name('receivables.')->namespace('Receivable')->group( function () {
    Route::resource('journals', 'ReceivableController')->except(['show']);
    Route::get('journals/export/excel', 'ReceivableController@exportExcel')->name('journals.index.export.excel');
    Route::resource('customers', 'CustomerController');
    Route::get('customers/export/excel', 'CustomerController@customersExportExcel')->name('customers.index.export.excel');
    Route::get('customers/{id}/export/excel', 'CustomerController@customerExportExcel')->name('customers.show.export.excel');
    Route::post('customers/types', 'CustomerController@storeType')->name('customers.types.store');
    Route::put('customers/types/{type}', 'CustomerController@updateType')->name('customers.types.update');
});

Route::middleware(['auth', 'role:Divisi Akuntansi|Divisi Hutang|supervisor'])->prefix('debts')->name('debts.')->namespace('Debt')->group(function () {
    Route::resource('journals', 'DebtController')->except(['show']);
    Route::get('journals/export/excel', 'DebtController@exportExcel')->name('journals.index.export.excel');
    Route::resource('clients', 'ClientController');
    Route::get('clients/export/excel', 'ClientController@clientsExportExcel')->name('clients.index.export.excel');
    Route::get('clients/{id}/export/excel', 'ClientController@clientExportExcel')->name('clients.show.export.excel');
    Route::post('clients/types', 'ClientController@storeType')->name('clients.types.store');
    Route::put('clients/types/{type}', 'ClientController@updateType')->name('clients.types.update');
});

Route::middleware(['auth', 'role:Divisi Akuntansi|Divisi Kas|supervisor'])->prefix('cashes')->name('cashes.')->namespace('Cash')->group(function () {
    Route::resource('entries', 'CashController')->except(['show']);
    Route::post('entries/create', 'CashController@storeAndCreate')->name('entries.store_and_create');
    Route::get('entries/export/excel', 'CashController@exportExcel')->name('entries.index.export.excel');
    Route::resource('banks', 'BankController');
    Route::get('banks/export/excel', 'BankController@banksExportExcel')->name('banks.index.export.excel');
    Route::get('banks/{id}/export/excel', 'BankController@bankExportExcel')->name('banks.show.export.excel');
    Route::post('banks/types', 'BankController@storeType')->name('banks.types.store');
    Route::put('banks/types/{type}', 'BankController@updateType')->name('banks.types.update');
});

// Route::prefix('roles')->name('roles.')->group(function () {
//     Route::get('/', 'IAM\IAMController@roleIndex')->name('index');
//     Route::post('/', 'IAM\IAMController@roleStore')->name('store');
//     Route::get('/{role}/edit','IAM\IAMController@roleEdit')->name('edit');
//     Route::put('/{role}','IAM\IAMController@roleUpdate')->name('update');
//     Route::delete('/{role}', 'IAM\IAMController@roleDestroy')->name('destroy');
// });

Route::prefix('users')->name('users.')->group(function () {
    Route::get('/', 'IAM\IAMController@userIndex')->name('index')->middleware('role:supervisor');
    Route::post('/', 'IAM\IAMController@userStore')->name('store')->middleware('role:superadmin|supervisor');
    Route::put('/update', 'IAM\IAMController@userUpdate')->name('update')->middleware('role:superadmin|supervisor');
    Route::get('/{user}/edit', 'IAM\IAMController@userEdit')->name('edit')->middleware('role:superadmin|supervisor');
    Route::delete('/{user}', 'IAM\IAMController@userDestroy')->name('destroy')->middleware('role:superadmin|supervisor');

    Route::get('/{user}/setting', 'Auth\ResetPasswordController@config')->name('config')->middleware('auth');
    Route::put('/{user}/update/password','Auth\ResetPasswordController@updatePassword')->name('update.password')->middleware('auth');

    Route::get('/forgot','Auth\ResetPasswordController@forgotPassword')->name('forgot-password')->middleware('guest');
    Route::post('/resetRequest','Auth\ResetPasswordController@passwordResetRequest')->name('reset-request')->middleware('guest');
    Route::post('/{user}/reset', 'Auth\ResetPasswordController@resetPassword')->name('reset-password')->middleware('role:supervisor');
    Route::post('/{user}/reject', 'Auth\ResetPasswordController@rejectResetRequest')->name('reject-request')->middleware('role:supervisor');
});

Route::middleware(['auth', 'role:superadmin'])->prefix('superadmins')->name('superadmins.')->group(function () {
    Route::get('/','IAM\IAMController@superadminIndex')->name('index');
});

//Company Routes

Route::middleware(['auth', 'role:superadmin|supervisor'])->prefix('companies')->name('companies.')->group(function () {
    Route::resource('/','Company\CompanyController')->parameters(['' => 'company']);
});

resources/views/home.blade.php
@extends('layouts.dashboard')

@section('dashboard-content')
    <div class="p-4">
        @role('superadmin')
            <div class="mb-4 d-flex align-items-center justify-content-between">
                <h1 class="h3 text-primary font-weight-bold mb-0"><i class="fas fa-th"></i> Data Perusahaan</h1>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Perusahaan</th>
                                    <th>Jenis Perusahaan</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($companies as $company)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $company->name }}</td>
                                        <td>{{ $company->company_type }}</td>
                                        <td class="text-center d-flex">
                                            <a href="" id="actionDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v text-gray-500"></i>
                                            </a>
                                            <!-- Dropdown - Companies Information -->
                                            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="actionDropdown">
                                            <a class="dropdown-item" href="{{ route('companies.edit', ['company' => $company]) }}">
                                                <i class="fas fa-eye fa-sm fa-fw mr-2 text-gray-400"></i>
                                                Lihat Data Perusahaan
                                            </a>
                                            <form action="{{ route('companies.destroy', ['company' => $company]) }}" method="POST">
                                                @csrf @method('DELETE')
                                                <button class="dropdown-item">
                                                    <i class="fas fa-trash text-gray-400 mr-2"></i>
                                                    Hapus Data
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        @endrole
        @role('supervisor')
            <div class="p-3">
                <div class="row">
                    <div class="col-md-4">
                        <a href="{{ route('receivables.journals.index') }}" class="card border-left-primary shadow h-100 py-2 card-link">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                            Data Piutang Belum Lengkap
                                        </div>
                                        <div class="h5 font-weight-bold text-gray-800 my-4">
                                            {{ $receivablesCount }} Data
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4">
                        <a href="{{ route('debts.journals.index') }}" class="card border-left-info shadow h-100 py-2 card-link">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                                            Data Hutang Belum Lengkap
                                        </div>
                                        <div class="h5 font-weight-bold text-gray-800 my-4">
                                            {{ $debtsCount }} Data
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-md-4">
                        <a href="{{ route('cashes.entries.index') }}" class="card border-left-danger shadow h-100 py-2 card-link">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
                                            Data Kas Belum Lengkap
                                        </div>
                                        <div class="h5 font-weight-bold text-gray-800 my-4">
                                            {{ $cashesCount }} Data
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        @endrole
        @role('Divisi Piutang')
        <div class="p-3">
            <div class="row">
                <div class="col-md-4">
                    <a href="{{ route('receivables.journals.index') }}" class="card border-left-primary shadow h-100 py-2 card-link">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                        Data Piutang Belum Lengkap
                                    </div>
                                    <div class="h5 font-weight-bold text-gray-800 my-4">
                                        {{ $receivablesCount }} Data
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        @endrole
        @role('Divisi Hutang')
        <div class="p-3">
            <div class="row">
                <div class="col-md-4">
                    <a href="{{ route('debts.journals.index') }}" class="card border-left-info shadow h-100 py-2 card-link">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                                        Data Hutang Belum Lengkap
                                    </div>
                                    <div class="h5 font-weight-bold text-gray-800 my-4">
                                        {{ $debtsCount }} Data
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        @endrole
        @role('Divisi Kas')
        <div class="p-3">
            <div class="row">
                <div class="col-md-4">
                    <a href="{{ route('cashes.entries.index') }}" class="card border-left-danger shadow h-100 py-2 card-link">
                        <div class="card-body">
                            <div class="row no-gutters align-items-center">
                                <div class="col mr-2">
                                    <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
                                        Data Kas Belum Lengkap
                                    </div>
                                    <div class="h5 font-weight-bold text-gray-800 my-4">
                                        {{ $cashesCount }} Data
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        @endrole
    </div>
@endsection

@push('scripts')
@endpush