routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes([
    'register' => false
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'role:Divisi Akuntansi|supervisor'])->group(function() {
    Route::resource('financial_statements', 'FinancialStatement\FinancialStatementController')
        ->only(['index', 'show']);
    Route::get('financial_statements/general_entries/export/excel', 'FinancialStatement\FinancialStatementController@exportGeneralEntriesExcel')->name('financial_statements.general_entries.export.excel');
    Route::get('financial_statements/balance_sheet/export/excel', 'FinancialStatement\FinancialStatementController@exportBalanceSheetExcel')->name('financial_statements.balance_sheet.export.excel');
    Route::get('financial_statements/income_statement/export/excel', 'FinancialStatement\FinancialStatementController@exportIncomeStatementExcel')->name('financial_statements.income_statement.export.excel');
});

Route::resource('accounts', 'Account\AccountController')->middleware(['auth', 'role:Divisi Akuntansi|supervisor']);

Route::middleware(['auth', 'role:Divisi Akuntansi|Divisi Piutang|supervisor'])->prefix('receivables')->name('receivables.')->namespace('Receivable')->group( function () {
    Route::resource('journals', 'ReceivableController')->except(['show']);
    Route::get('journals/export/excel', 'ReceivableController@exportExcel')->name('journals.index.export.excel');
    Route::resource('customers', 'CustomerController');
    Route::get('customers/export/excel', 'CustomerController@customersExportExcel')->name('customers.index.export.excel');
    Route::get('customers/{id}/export/excel', 'CustomerController@customerExportExcel')->name('customers.show.export.excel');
    Route::post('customers/types', 'CustomerController@storeType')->name('customers.types.store');
    Route::put('customers/types/{type}', 'CustomerController@updateType')->name('customers.types.update');
});

Route::middleware(['auth', 'role:Divisi Akuntansi|Divisi Hutang|supervisor'])->prefix('debts')->name('debts.')->namespace('Debt')->group(function () {
    Route::resource('journals', 'DebtController')->except(['show']);
    Route::get('journals/export/excel', 'DebtController@exportExcel')->name('journals.index.export.excel');
    Route::resource('clients', 'ClientController');
    Route::get('clients/export/excel', 'ClientController@clientsExportExcel')->name('clients.index.export.excel');
    Route::get('clients/{id}/export/excel', 'ClientController@clientExportExcel')->name('clients.show.export.excel');
    Route::post('clients/types', 'ClientController@storeType')->name('clients.types.store');
    Route::put('clients/types/{type}', 'ClientController@updateType')->name('clients.types.update');
});

Route::middleware(['auth', 'role:Divisi Akuntansi|Divisi Kas|supervisor'])->prefix('cashes')->name('cashes.')->namespace('Cash')->group(function () {
    Route::resource('entries', 'CashController')->except(['show']);
    Route::post('entries/create', 'CashController@storeAndCreate')->name('entries.store_and_create');
    Route::get('entries/export/excel', 'CashController@exportExcel')->name('entries.index.export.excel');
    Route::resource('banks', 'BankController');
    Route::get('banks/export/excel', 'BankController@banksExportExcel')->name('banks.index.export.excel');
    Route::get('banks/{id}/export/excel', 'BankController@bankExportExcel')->name('banks.show.export.excel');
    Route::post('banks/types', 'BankController@storeType')->name('banks.types.store');
    Route::put('banks/types/{type}', 'BankController@updateType')->name('banks.types.update');
});

// Route::prefix('roles')->name('roles.')->group(function () {
//     Route::get('/', 'IAM\IAMController@roleIndex')->name('index');
//     Route::post('/', 'IAM\IAMController@roleStore')->name('store');
//     Route::get('/{role}/edit','IAM\IAMController@roleEdit')->name('edit');
//     Route::put('/{role}','IAM\IAMController@roleUpdate')->name('update');
//     Route::delete('/{role}', 'IAM\IAMController@roleDestroy')->name('destroy');
// });

Route::prefix('users')->name('users.')->group(function () {
    Route::get('/', 'IAM\IAMController@userIndex')->name('index')->middleware('role:supervisor');
    Route::post('/', 'IAM\IAMController@userStore')->name('store')->middleware('role:superadmin|supervisor');
    Route::put('/update', 'IAM\IAMController@userUpdate')->name('update')->middleware('role:superadmin|supervisor');
    Route::get('/{user}/edit', 'IAM\IAMController@userEdit')->name('edit')->middleware('role:superadmin|supervisor');
    Route::delete('/{user}', 'IAM\IAMController@userDestroy')->name('destroy')->middleware('role:superadmin|supervisor');

    Route::get('/{user}/setting', 'Auth\ResetPasswordController@config')->name('config')->middleware('auth');
    Route::put('/{user}/update/password','Auth\ResetPasswordController@updatePassword')->name('update.password')->middleware('auth');

    Route::get('/forgot','Auth\ResetPasswordController@forgotPassword')->name('forgot-password')->middleware('guest');
    Route::post('/resetRequest','Auth\ResetPasswordController@passwordResetRequest')->name('reset-request')->middleware('guest');
    Route::post('/{user}/reset', 'Auth\ResetPasswordController@resetPassword')->name('reset-password')->middleware('role:supervisor');
    Route::post('/{user}/reject', 'Auth\ResetPasswordController@rejectResetRequest')->name('reject-request')->middleware('role:supervisor');
});

Route::middleware(['auth', 'role:superadmin'])->prefix('superadmins')->name('superadmins.')->group(function () {
    Route::get('/','IAM\IAMController@superadminIndex')->name('index');
});

//Company Routes

Route::middleware(['auth', 'role:superadmin|supervisor'])->prefix('companies')->name('companies.')->group(function () {
    Route::resource('/','Company\CompanyController')->parameters(['' => 'company']);
});

app/Models/Cash.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cash extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function debitAccount(){
        return $this->belongsTo(Account::class, 'debit_account_id');
    }

    public function creditAccount(){
        return $this->belongsTo(Account::class, 'credit_account_id');
    }

    public function bank(){
        return $this->belongsTo(Bank::class, 'bank_id');
    }

    public function receivable(){
        return $this->hasOne(Receivable::class, 'cash_id');
    }

    public function debt(){
        return $this->hasOne(Debt::class, 'cash_id');
    }
}

app/Http/Controllers/Cash/BankController.php
<?php

namespace App\Http\Controllers\Cash;

use App\Exports\BankReport;
use App\Exports\BanksReport;
use App\Http\Controllers\Controller;
use App\Http\Requests\BankStoreRequest;
use App\Http\Requests\BankTypeStoreRequest;
use App\Http\Requests\BankTypeUpdateRequest;
use App\Http\Requests\BankUpdateRequest;
use App\Repositories\Cash\Bank\BankRepositoryInterface;
use App\Repositories\Cash\Bank\BankTypeRepositoryInterface;
use App\Services\ExportService;
use Illuminate\Http\Request;

class BankController extends Controller
{
    private BankRepositoryInterface $bankRepository;
    private BankTypeRepositoryInterface $bankTypeRepository;

    public function __construct(BankRepositoryInterface $bankRepository, BankTypeRepositoryInterface $bankTypeRepository)
    {
        $this->bankRepository = $bankRepository;
        $this->bankTypeRepository = $bankTypeRepository;
    }

    public function index(Request $request)
    {
        $bankTypes = $this->bankTypeRepository->getAllByRange($request);
        $banks = $this->bankRepository->getAllByRange($request);

        return view('cashes.banks.index', compact('banks', 'bankTypes'));
    }

    public function create()
    {
        $bankTypes = $this->bankTypeRepository->getAll();

        return view('cashes.banks.create', compact('bankTypes'));
    }

    public function store(BankStoreRequest $request)
    {
        $this->bankRepository->create($request->validated());

        return redirect(route('cashes.banks.index'));
    }

    public function show(Request $request, $id)
    {
        $bank = $this->bankRepository->findByIdAndRange($id, $request);

        return view('cashes.banks.show', compact('bank'));
    }

    public function edit($id)
    {
        $bank = $this->bankRepository->findById($id);
        $bankTypes = $this->bankTypeRepository->getAll();

        return view('cashes.banks.edit', compact('bank', 'bankTypes'));
    }

    public function update(BankUpdateRequest $request, $id)
    {
        $this->bankRepository->update($id, $request->validated());

        return redirect(route('cashes.banks.index'));
    }

    public function destroy($id)
    {
        $this->bankRepository->delete($id);

        return redirect(route('cashes.banks.index'));
    }

    public function storeType(BankTypeStoreRequest $request){
        $this->bankTypeRepository->create($request->validated());

        return redirect(route('cashes.banks.create'));
    }

    public function updateType(BankTypeUpdateRequest $request, $id){
        $this->bankTypeRepository->update($id, $request->validated());

        return redirect(route('cashes.banks.index'));
    }

    public function bankExportExcel(Request $request, $id, ExportService $exportService){
        $bank = $this->bankRepository->findByIdAndRange($id, $request);
        $bankCode = $bank->code;
        $rangeDate = $exportService->setData($request)
            ->getRangeDateText();

        return (new BankReport($bank, $rangeDate))->download("Kartu_${bankCode}_${rangeDate}.xlsx");
    }

    public function banksExportExcel(Request $request, ExportService $exportService){
        $bankTypes = $this->bankTypeRepository->getAllByRange($request);
        $banks = $this->bankRepository->getAllByRange($request);
        $rangeDate = $exportService->setData($request)
            ->getRangeDateText();

        return (new BanksReport($banks, $bankTypes, $rangeDate))->download("Rekapitulasi Kas_${rangeDate}.xlsx");
    }
}

app/Http/Controllers/Cash/CashController.php
<?php

namespace App\Http\Controllers\Cash;

use App\Exports\CashesReport;
use App\Http\Controllers\Controller;
use App\Http\Requests\CashStoreRequest;
use App\Http\Requests\CashUpdateRequest;
use App\Repositories\Account\AccountRepositoryInterface;
use App\Repositories\Cash\Bank\BankRepositoryInterface;
use App\Repositories\Cash\CashRepositoryInterface;
use App\Services\ExportService;
use Illuminate\Http\Request;

class CashController extends Controller
{
    private CashRepositoryInterface $cashRepository;

    public function __construct(CashRepositoryInterface $cashRepository)
    {
        $this->cashRepository = $cashRepository;
    }

    public function index(Request $request)
    {
        $cashes = $this->cashRepository
            ->getAllByRange($request);

        return view('cashes.entries.index', compact('cashes'));
    }

    public function create(BankRepositoryInterface $bankRepository, AccountRepositoryInterface $accountRepository)
    {
        $banks = $bankRepository->getAll();
        $accounts = $accountRepository->getAll();

        return view('cashes.entries.create', compact('banks', 'accounts'));
    }

    public function store(CashStoreRequest $request)
    {
        $this->cashRepository->create($request->validated());

        return redirect(route('cashes.entries.index'));
    }

    public function storeAndCreate(CashStoreRequest $request)
    {
        $this->cashRepository->create($request->validated());
        
        return redirect(route('cashes.entries.create'))->with('status', 'Menambah entry baru berhasil!');
    }

    public function edit($id, BankRepositoryInterface $bankRepository, AccountRepositoryInterface $accountRepository)
    {
        $cash = $this->cashRepository->findById($id);
        $banks = $bankRepository->getAll();
        $accounts = $accountRepository->getAll();
        return view('cashes.entries.edit', compact('cash', 'banks','accounts'));
    }

    public function update(CashUpdateRequest $request, $id)
    {
        $this->cashRepository->update($id, $request->validated());

        return redirect(route('cashes.entries.index'));
    }

    public function destroy($id)
    {
        $this->cashRepository->delete($id);

        return redirect(route('cashes.entries.index'));
    }

    public function exportExcel(Request $request, ExportService $exportService){
        $cashes = $this->cashRepository
            ->getAllByRange($request);
        $rangeDate = $exportService->setData($request)
            ->getRangeDateText();

        return (new CashesReport($cashes, $rangeDate))->download("Entry Kas_${rangeDate}.xlsx");
    }
}

resources/views/cashes/entries/create.blade.php
@extends('layouts.dashboard')

@section('dashboard-content')
    <div class="p-4">
        <!-- Page Heading -->
        <div class="mb-4 d-flex align-items-center justify-content-between">
            <h1 class="h3 text-primary font-weight-bold mb-0">Tambah Transaksi Kas dan Bank</h1>
        </div>

        <div class="card shadow-sm">
            <form id="form" class="card-body" action="{{route('cashes.entries.store')}}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <x-inputs.select
                            label="Bank"
                            name="bank"
                            placeholder="Pilih bank"
                            search
                            :option-values="$banks->map(fn($bank)=>$bank->id)"
                            :option-names="$banks->map(fn($bank)=>$bank->name)"
                        />
                        <x-inputs.input
                            label="Tanggal"
                            name="date"
                            type="date"
                            :value="date('Y-m-d')"
                            required/>
                        <x-inputs.textarea
                            label="Uraian"
                            name="description"
                            rows="3"
                            placeholder="Masukkan uraian"/>
                        <x-inputs.input
                            label="No. Bukti"
                            name="invoice_num"
                            placeholder="Masukkan no. bukti"/>
                    </div>
                    <div class="col-md-6">
                        <div class="form-row">
                            <div class="form-group col-6">
                                <div class="custom-control custom-radio">
                                    <input type="radio" id="billType" name="type" class="custom-control-input" value="bill" checked>
                                    <label class="custom-control-label" for="billType">Pemasukan</label>
                                </div>
                            </div>
                            <div class="form-group col-6">
                                <div class="custom-control custom-radio">
                                    <input type="radio" id="paymentType" name="type" class="custom-control-input" value="payment">
                                    <label class="custom-control-label" for="paymentType">Pengeluaran</label>
                                </div>
                            </div>
                        </div>
                        <x-inputs.input
                            label="Nilai Pemasukan"
                            name="bill_value"
                            id="billValue"
                            type="number"
                            step="0.001"
                            placeholder="Masukkan nilai pemasukan"/>
                        <x-inputs.input
                            label="Nilai Pengeluaran"
                            name="payment_value"
                            id="paymentValue"
                            type="number"
                            step="0.001"
                            disabled
                            placeholder="Masukkan nilai pengeluaran"/>
                        <x-inputs.textarea
                            label="Keterangan"
                            name="information"
                            rows="3"
                            placeholder="Masukkan keterangan..."/>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-6">
                        <x-inputs.select
                            label="Akun Debit"
                            name="debit_account"
                            placeholder="Pilih akun"
                            search
                            :option-values="$accounts->map(fn($acc)=>$acc->id)"
                            :option-names="$accounts->map(fn($acc)=>$acc->account_num.' - '.$acc->name)"
                        />
                    </div>
                    <div class="col-md-6">
                        <x-inputs.select
                            label="Akun Kredit"
                            name="credit_account"
                            placeholder="Pilih akun"
                            search
                            :option-values="$accounts->map(fn($acc)=>$acc->id)"
                            :option-names="$accounts->map(fn($acc)=>$acc->account_num.' - '.$acc->name)"
                        />
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-12 text-right">
                        <a href="{{route('cashes.entries.index')}}" class="btn btn-light mr-3">Batal</a>
                        <button class="btn btn-primary"><i class="fas fa-save"></i> Tambah</button>
                        <button id="buttonStoreAndCreate" type="button" class="btn btn-primary"><i class="fas fa-plus"></i> Tambah dan Buat Lagi</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection


@push('scripts')
    <script>
        $(document).ready( function () {
            const typeChecks = $("input[name='type']");
            typeChecks.change(function(){
                if(this.checked){
                    updateTransactionInput($(this).val());
                }
            });

            function updateTransactionInput (type){
                if(type === 'bill'){
                    $('#billValue').prop('disabled', false);
                    $('#paymentValue').prop('disabled', true);
                } else if(type === 'payment') {
                    $('#billValue').prop('disabled', true);
                    $('#paymentValue').prop('disabled', false);
                }
            }

            document.getElementById('buttonStoreAndCreate').addEventListener('click', () => {
                const form = document.getElementById('form');
                form.setAttribute('action', "{{ route('cashes.entries.store_and_create') }}");
                form.submit();
            });
        } );
    </script>
@endpush

resources/views/cashes/entries/index.blade.php
@extends('layouts.dashboard')

@section('dashboard-content')
    <div class="p-4">
        <!-- Page Heading -->
        <div class="mb-4 d-flex align-items-center justify-content-between">
            <h1 class="h3 text-primary font-weight-bold mb-0">Entry Kas dan Bank</h1>
        </div>

        <div class="mb-4 d-flex flex-column align-items-end flex-md-row justify-content-md-between align-items-md-center">
            <div class="align-self-start">
                <x-period-filter :route="route('cashes.entries.index')" />
            </div>
            <div class="mt-3 mt-md-0 d-flex">
                <x-btn-export :route="route('cashes.entries.index.export.excel')" class="mr-1"/>
                <a href="{{route('cashes.entries.create')}}" class="btn btn-primary">
                    <i class="fas fa-plus"></i> Tambah Transaksi Kas dan Bank
                </a>
            </div>
        </div>

        <div class="card shadow-sm">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover data-table" width="100%" cellspacing="0">
                        <thead>
                        <tr class="text-uppercase small text-primary">
                            <th>No.</th>
                            <th>Tanggal</th>
                            <th>Nama Kas/Bank</th>
                            <th>Uraian</th>
                            <th>Masuk</th>
                            <th>Keluar</th>
                            <th>Status</th>
                            <th>Aksi</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th class="text-right" colspan="4">Total</th>
                            <th class="text-right">Rp <span class="mask-money">{{$cashes->reduce(fn($sum,$item)=>$sum+$item->bill_value)}}</span></th>
                            <th class="text-right">Rp <span class="mask-money">{{$cashes->reduce(fn($sum,$item)=>$sum+$item->payment_value)}}</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </tfoot>
                        <tbody>
                        @foreach ($cashes as $cash)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>
                                    {{(new Carbon\Carbon($cash->date))->format('d M Y')}}
                                </td>
                                <td>
                                    @if ($cash->bank)
                                        {{$cash->bank->name}} <br>
                                        <small class="text-gray-500">{{$cash->bank->code}}</small>
                                    @else
                                        <div class="badge badge-danger rounded-pill px-2 py-1">Unknown</div>
                                    @endif
                                </td>
                                <td>{{$cash->description ?? '-'}}</td>
                                <td class="text-right">Rp <span class="mask-money">{{$cash->bill_value ?? 0}}</span></td>
                                <td class="text-right">Rp <span class="mask-money">{{$cash->payment_value ?? 0}}</span></td>
                                <td class="text-center">
                                    @if($cash->is_complete)
                                        <div class="badge badge-success rounded-pill px-2 py-1">Complete</div>
                                    @else
                                        <div class="badge badge-danger rounded-pill px-2 py-1">Incomplete</div>
                                    @endif
                                </td>
                                <td class="text-center">
                                    <a href="" id="actionDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-ellipsis-v text-gray-500"></i>
                                    </a>
                                    <!-- Dropdown - User Information -->
                                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="actionDropdown">
                                        @if ($cash->bank)
                                            <a class="dropdown-item" href="{{route('cashes.banks.show', $cash->bank->id)}}">
                                                <i class="fas fa-eye fa-sm fa-fw mr-2 text-gray-400"></i>
                                                Lihat Bank
                                            </a>
                                        @endif
                                        <a class="dropdown-item" href="{{route('cashes.entries.edit', $cash->id)}}">
                                            <i class="fas fa-edit fa-sm fa-fw mr-2 text-gray-400"></i>
                                            Sunting
                                        </a>
                                        <a class="dropdown-item delete" href="{{route('cashes.entries.destroy', $cash->id)}}">
                                            <i class="fas fa-trash fa-sm fa-fw mr-2 text-gray-400"></i>
                                            Hapus
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function () {
            $('body').on('click', '.delete', function (event) {
                event.preventDefault();
                let action = $(this).attr('href');
                $('#deleteForm').attr('action', action);
                $('#deleteModal').modal('show');
            });
        });
    </script>
@endpush

@push('modals')
    <div>
        <!-- Delete Modal-->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <form id="deleteForm" class="modal-content" method="POST">
                    @csrf
                    @method('DELETE')
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Apakah Anda Yakin?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Data akan terhapus permanen jika anda menghapusnya.</div>
                    <div class="modal-footer">
                        <button class="btn btn-light" type="button" data-dismiss="modal">Batal</button>
                        <button type="submit" class="btn btn-danger">
                            <i class="fas fa-trash mr-1"></i>
                            Hapus
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <!-- End of Modal -->
    </div>
@endpush