routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes([
    'register' => false
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'role:Divisi Akuntansi|supervisor'])->group(function() {
    Route::resource('financial_statements', 'FinancialStatement\FinancialStatementController')
        ->only(['index', 'show']);
    Route::get('financial_statements/general_entries/export/excel', 'FinancialStatement\FinancialStatementController@exportGeneralEntriesExcel')->name('financial_statements.general_entries.export.excel');
    Route::get('financial_statements/balance_sheet/export/excel', 'FinancialStatement\FinancialStatementController@exportBalanceSheetExcel')->name('financial_statements.balance_sheet.export.excel');
    Route::get('financial_statements/income_statement/export/excel', 'FinancialStatement\FinancialStatementController@exportIncomeStatementExcel')->name('financial_statements.income_statement.export.excel');
});

Route::resource('accounts', 'Account\AccountController')->middleware(['auth', 'role:Divisi Akuntansi|supervisor']);

Route::middleware(['auth', 'role:Divisi Akuntansi|Divisi Piutang|supervisor'])->prefix('receivables')->name('receivables.')->namespace('Receivable')->group( function () {
    Route::resource('journals', 'ReceivableController')->except(['show']);
    Route::get('journals/export/excel', 'ReceivableController@exportExcel')->name('journals.index.export.excel');
    Route::resource('customers', 'CustomerController');
    Route::get('customers/export/excel', 'CustomerController@customersExportExcel')->name('customers.index.export.excel');
    Route::get('customers/{id}/export/excel', 'CustomerController@customerExportExcel')->name('customers.show.export.excel');
    Route::post('customers/types', 'CustomerController@storeType')->name('customers.types.store');
    Route::put('customers/types/{type}', 'CustomerController@updateType')->name('customers.types.update');
});

Route::middleware(['auth', 'role:Divisi Akuntansi|Divisi Hutang|supervisor'])->prefix('debts')->name('debts.')->namespace('Debt')->group(function () {
    Route::resource('journals', 'DebtController')->except(['show']);
    Route::get('journals/export/excel', 'DebtController@exportExcel')->name('journals.index.export.excel');
    Route::resource('clients', 'ClientController');
    Route::get('clients/export/excel', 'ClientController@clientsExportExcel')->name('clients.index.export.excel');
    Route::get('clients/{id}/export/excel', 'ClientController@clientExportExcel')->name('clients.show.export.excel');
    Route::post('clients/types', 'ClientController@storeType')->name('clients.types.store');
    Route::put('clients/types/{type}', 'ClientController@updateType')->name('clients.types.update');
});

Route::middleware(['auth', 'role:Divisi Akuntansi|Divisi Kas|supervisor'])->prefix('cashes')->name('cashes.')->namespace('Cash')->group(function () {
    Route::resource('entries', 'CashController')->except(['show']);
    Route::post('entries/create', 'CashController@storeAndCreate')->name('entries.store_and_create');
    Route::get('entries/export/excel', 'CashController@exportExcel')->name('entries.index.export.excel');
    Route::resource('banks', 'BankController');
    Route::get('banks/export/excel', 'BankController@banksExportExcel')->name('banks.index.export.excel');
    Route::get('banks/{id}/export/excel', 'BankController@bankExportExcel')->name('banks.show.export.excel');
    Route::post('banks/types', 'BankController@storeType')->name('banks.types.store');
    Route::put('banks/types/{type}', 'BankController@updateType')->name('banks.types.update');
});

// Route::prefix('roles')->name('roles.')->group(function () {
//     Route::get('/', 'IAM\IAMController@roleIndex')->name('index');
//     Route::post('/', 'IAM\IAMController@roleStore')->name('store');
//     Route::get('/{role}/edit','IAM\IAMController@roleEdit')->name('edit');
//     Route::put('/{role}','IAM\IAMController@roleUpdate')->name('update');
//     Route::delete('/{role}', 'IAM\IAMController@roleDestroy')->name('destroy');
// });

Route::prefix('users')->name('users.')->group(function () {
    Route::get('/', 'IAM\IAMController@userIndex')->name('index')->middleware('role:supervisor');
    Route::post('/', 'IAM\IAMController@userStore')->name('store')->middleware('role:superadmin|supervisor');
    Route::put('/update', 'IAM\IAMController@userUpdate')->name('update')->middleware('role:superadmin|supervisor');
    Route::get('/{user}/edit', 'IAM\IAMController@userEdit')->name('edit')->middleware('role:superadmin|supervisor');
    Route::delete('/{user}', 'IAM\IAMController@userDestroy')->name('destroy')->middleware('role:superadmin|supervisor');

    Route::get('/{user}/setting', 'Auth\ResetPasswordController@config')->name('config')->middleware('auth');
    Route::put('/{user}/update/password','Auth\ResetPasswordController@updatePassword')->name('update.password')->middleware('auth');

    Route::get('/forgot','Auth\ResetPasswordController@forgotPassword')->name('forgot-password')->middleware('guest');
    Route::post('/resetRequest','Auth\ResetPasswordController@passwordResetRequest')->name('reset-request')->middleware('guest');
    Route::post('/{user}/reset', 'Auth\ResetPasswordController@resetPassword')->name('reset-password')->middleware('role:supervisor');
    Route::post('/{user}/reject', 'Auth\ResetPasswordController@rejectResetRequest')->name('reject-request')->middleware('role:supervisor');
});

Route::middleware(['auth', 'role:superadmin'])->prefix('superadmins')->name('superadmins.')->group(function () {
    Route::get('/','IAM\IAMController@superadminIndex')->name('index');
});

//Company Routes

Route::middleware(['auth', 'role:superadmin|supervisor'])->prefix('companies')->name('companies.')->group(function () {
    Route::resource('/','Company\CompanyController')->parameters(['' => 'company']);
});

app/Http/Controllers/IAM/IAMController.php
<?php

namespace App\Http\Controllers\IAM;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\RoleStoreRequest;
use App\Http\Requests\RoleUpdateRequest;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Repositories\User\UserRepositoryInterface;
use App\Repositories\Roles\RoleRepositoryInterface;
use App\Repositories\Permission\PermissionRepositoryInterface;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Company;
use Spatie\Permission\Models\Role;

class IAMController extends Controller
{
    private $roleRepository;
    private $permissionRepository;
    private $userRepository;

    /**
     * Identity and Access Management Controller Constructor
     * @param RoleRepositoryInterface $roleRepository
     * @param PermissionRepositoryInterface $permissionRepository
     */
    public function __construct(RoleRepositoryInterface $roleRepository, PermissionRepositoryInterface $permissionRepository, UserRepositoryInterface $userRepository)
    {
        $this->roleRepository = $roleRepository;
        $this->permissionRepository = $permissionRepository;
        $this->userRepository = $userRepository;
    }

    public function userIndex()
    {
        $users = User::where('company_id',Auth::user()->company_id)
            ->whereHas('roles', function($q) {
                $q->where('id','>',2);
            })->get();
        $companies = Company::all();
        $requesting_reset = User::where('company_id',Auth::user()->company_id)
            ->where('is_requesting_password_reset',1)->get();
        $roles = Role::all();

        return view('IAM.index', compact('users','companies','roles','requesting_reset'));
    }

    public function userStore(UserStoreRequest $request)
    {
        $this->userRepository->create($request->validated());
        return redirect()->back();
    }

    public function userEdit(User $user)
    {
        $companies = Company::all();
        $roles = Role::all();
        return view('iam.users.edit',compact('user','companies','roles'));
    }

    public function userUpdate(UserUpdateRequest $request)
    {
        if($this->userRepository->update($request->validated()['user_id'],$request->validated())) return redirect()->back();
    }

    public function userDestroy(User $user)
    {
        if($this->userRepository->delete($user->id)) return redirect()->back();
    }

    /**
     * Superadmin methods
     */

    public function superadminIndex()
    {
        $superadmins = Role::find(1)->users()->get();
        return view('IAM.superadmins.index',compact('superadmins'));
    }

    /**
     * Display a listing of ROLE RESOURCE
     * 
     */
    public function roleIndex()
    {
        $roles = $this->roleRepository->getAll();
        $permissions = $this->permissionRepository->getAll();
        return view('IAM.roles.index', compact('roles','permissions'));
    }

    public function roleStore(RoleStoreRequest $request)
    {
        $storeNewRole = $this->roleRepository->create($request);
        if($storeNewRole) return redirect(route('roles.index'));
    }

    public function roleEdit(Role $role)
    {
        $rolePermissions = $role->permissions->pluck('name');
        $users = User::role($role)->get();
        $permissions = $this->permissionRepository->getAll();
        return view('IAM.roles.edit', compact('role','rolePermissions','users','permissions'));
    }

    public function roleUpdate(RoleUpdateRequest $request,Role $role)
    {
        $this->roleRepository->update($role->id,$request->validated());
        return redirect(route('roles.index'));
    }

    public function roleDestroy(Role $role)
    {
        $this->roleRepository->delete($role->id);
        return redirect(route('roles.index'));
    }
}

resources/views/IAM/index.blade.php
@extends('layouts.dashboard')

@section('dashboard-content')
    <div class="p-4">
        <!-- Page Heading -->
        <div class="mb-4 d-flex align-items-center justify-content-between">
            <h1 class="h3 text-primary font-weight-bold mb-0"><i class="fas fa-users"></i> Data Pegawai Perusahaan</h1>
            <button class="btn btn-primary" data-toggle="collapse" data-target="#createUser" aria-expanded="false" aria-controls="collapseForm">
                <i class="fas fa-plus"></i> Tambah Pegawai Baru
            </button>

        </div>
        
        <div class="card mb-4 collapse" id="createUser">
            <div class="card-body">
                <form action="{{ route('users.store') }}" method="POST">
                    @csrf
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <h4>Tambah User Baru</h4>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <x-inputs.input
                                label="Nama"
                                name="name"
                                type="text"
                                placeholder="Masukkan Nama User Baru"
                                required
                            />
                            <x-inputs.input
                                label="Username"
                                name="username"
                                type="text"
                                placeholder="Username untuk user baru"
                                required
                            />
                            <x-inputs.input
                                label="Email"
                                name="email"
                                type="text"
                                placeholder="Email untuk user baru"
                                required
                            />
                        </div>
                        <div class="col-md-6">
                            <x-inputs.input
                                disabled
                                label="Default password untuk user baru adalah:"
                                name="password"
                                type="password"
                                placeholder="SecurePassword2020"
                            />
                            <x-inputs.select
                                label="Role"
                                name="role_id"
                                placeholder="Pilih role user"
                                search
                                :option-values="$roles->map(fn($role)=>$role->id)->filter(function($role, $key){return $key > 1;})"
                                :option-names="$roles->map(fn($role)=>$role->name)->filter(function($role, $key){return $key > 1;})"
                            />
                            <x-inputs.input
                                name="company_id"
                                value="{{ Auth::user()->company_id }}"
                                hidden
                            />
                            <button class="btn btn-primary float-right"> Tambah User</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="card mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Company</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $user)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->username }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ $user->roles->map(function ($role){return $role->name;})->implode(', ') }}</td>
                                    <td>{{ $user->company->name }}</td>
                                    <td class="text-center">
                                        <a href="" id="actionDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v text-gray-500"></i>
                                        </a>
                                        <!-- Dropdown - User Information -->
                                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="actionDropdown">
                                        <a class="dropdown-item" href="{{ route('users.edit', ['user' => $user]) }}">
                                            <i class="fas fa-eye fa-sm fa-fw mr-2 text-gray-400"></i>
                                            Edit Data
                                        </a>
                                        <form action="{{ route('users.destroy', ['user' => $user->id]) }}" method="POST">
                                            @csrf @method('DELETE')
                                            <button class="dropdown-item">
                                                <i class="fas fa-trash text-gray-400 mr-2"></i>
                                                Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        @if ($requesting_reset->count() > 0)
            <div class="mb-4 d-flex align-items-center justify-content-between">
                <h1 class="h3 text-primary font-weight-bold mb-0"><i class="fas fa-key"></i> Permintaan Reset Password</h1>
            </div>

            <div class="card mb-4">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover data-table" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Username</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($requesting_reset as $req)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $req->name }}</td>
                                        <td>{{ $req->username }}</td>
                                        <td>{{ $req->email }}</td>
                                        <td>{{ $req->roles->map(function ($role){return $role->name;})->implode(', ') }}</td>
                                        <td class="text-center">
                                            <a href="" id="actionDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                <i class="fas fa-ellipsis-v text-gray-500"></i>
                                            </a>
                                            <!-- Dropdown - User Information -->
                                            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="actionDropdown">
                                                <form action="{{ route('users.reset-password', ['user' => $req->id]) }}" method="POST">
                                                    @csrf
                                                    <button class="dropdown-item">
                                                        <i class="fas fa-key fa-sm fa-fw mr-2 text-gray-400"></i>
                                                        Reset Password
                                                    </button>
                                                </form>
                                                <form action="{{ route('users.reject-request', ['user' => $req->id]) }}" method="POST">
                                                    @csrf
                                                    <button class="dropdown-item">
                                                        <i class="fas fa-trash text-gray-400 mr-2"></i>
                                                        Abaikan
                                                    </button>
                                                </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection