routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('login'));
});

Auth::routes([
    'register' => false
]);

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'role:Divisi Akuntansi|supervisor'])->group(function() {
    Route::resource('financial_statements', 'FinancialStatement\FinancialStatementController')
        ->only(['index', 'show']);
    Route::get('financial_statements/general_entries/export/excel', 'FinancialStatement\FinancialStatementController@exportGeneralEntriesExcel')->name('financial_statements.general_entries.export.excel');
    Route::get('financial_statements/balance_sheet/export/excel', 'FinancialStatement\FinancialStatementController@exportBalanceSheetExcel')->name('financial_statements.balance_sheet.export.excel');
    Route::get('financial_statements/income_statement/export/excel', 'FinancialStatement\FinancialStatementController@exportIncomeStatementExcel')->name('financial_statements.income_statement.export.excel');
});

Route::resource('accounts', 'Account\AccountController')->middleware(['auth', 'role:Divisi Akuntansi|supervisor']);

Route::middleware(['auth', 'role:Divisi Akuntansi|Divisi Piutang|supervisor'])->prefix('receivables')->name('receivables.')->namespace('Receivable')->group( function () {
    Route::resource('journals', 'ReceivableController')->except(['show']);
    Route::get('journals/export/excel', 'ReceivableController@exportExcel')->name('journals.index.export.excel');
    Route::resource('customers', 'CustomerController');
    Route::get('customers/export/excel', 'CustomerController@customersExportExcel')->name('customers.index.export.excel');
    Route::get('customers/{id}/export/excel', 'CustomerController@customerExportExcel')->name('customers.show.export.excel');
    Route::post('customers/types', 'CustomerController@storeType')->name('customers.types.store');
    Route::put('customers/types/{type}', 'CustomerController@updateType')->name('customers.types.update');
});

Route::middleware(['auth', 'role:Divisi Akuntansi|Divisi Hutang|supervisor'])->prefix('debts')->name('debts.')->namespace('Debt')->group(function () {
    Route::resource('journals', 'DebtController')->except(['show']);
    Route::get('journals/export/excel', 'DebtController@exportExcel')->name('journals.index.export.excel');
    Route::resource('clients', 'ClientController');
    Route::get('clients/export/excel', 'ClientController@clientsExportExcel')->name('clients.index.export.excel');
    Route::get('clients/{id}/export/excel', 'ClientController@clientExportExcel')->name('clients.show.export.excel');
    Route::post('clients/types', 'ClientController@storeType')->name('clients.types.store');
    Route::put('clients/types/{type}', 'ClientController@updateType')->name('clients.types.update');
});

Route::middleware(['auth', 'role:Divisi Akuntansi|Divisi Kas|supervisor'])->prefix('cashes')->name('cashes.')->namespace('Cash')->group(function () {
    Route::resource('entries', 'CashController')->except(['show']);
    Route::post('entries/create', 'CashController@storeAndCreate')->name('entries.store_and_create');
    Route::get('entries/export/excel', 'CashController@exportExcel')->name('entries.index.export.excel');
    Route::resource('banks', 'BankController');
    Route::get('banks/export/excel', 'BankController@banksExportExcel')->name('banks.index.export.excel');
    Route::get('banks/{id}/export/excel', 'BankController@bankExportExcel')->name('banks.show.export.excel');
    Route::post('banks/types', 'BankController@storeType')->name('banks.types.store');
    Route::put('banks/types/{type}', 'BankController@updateType')->name('banks.types.update');
});

// Route::prefix('roles')->name('roles.')->group(function () {
//     Route::get('/', 'IAM\IAMController@roleIndex')->name('index');
//     Route::post('/', 'IAM\IAMController@roleStore')->name('store');
//     Route::get('/{role}/edit','IAM\IAMController@roleEdit')->name('edit');
//     Route::put('/{role}','IAM\IAMController@roleUpdate')->name('update');
//     Route::delete('/{role}', 'IAM\IAMController@roleDestroy')->name('destroy');
// });

Route::prefix('users')->name('users.')->group(function () {
    Route::get('/', 'IAM\IAMController@userIndex')->name('index')->middleware('role:supervisor');
    Route::post('/', 'IAM\IAMController@userStore')->name('store')->middleware('role:superadmin|supervisor');
    Route::put('/update', 'IAM\IAMController@userUpdate')->name('update')->middleware('role:superadmin|supervisor');
    Route::get('/{user}/edit', 'IAM\IAMController@userEdit')->name('edit')->middleware('role:superadmin|supervisor');
    Route::delete('/{user}', 'IAM\IAMController@userDestroy')->name('destroy')->middleware('role:superadmin|supervisor');

    Route::get('/{user}/setting', 'Auth\ResetPasswordController@config')->name('config')->middleware('auth');
    Route::put('/{user}/update/password','Auth\ResetPasswordController@updatePassword')->name('update.password')->middleware('auth');

    Route::get('/forgot','Auth\ResetPasswordController@forgotPassword')->name('forgot-password')->middleware('guest');
    Route::post('/resetRequest','Auth\ResetPasswordController@passwordResetRequest')->name('reset-request')->middleware('guest');
    Route::post('/{user}/reset', 'Auth\ResetPasswordController@resetPassword')->name('reset-password')->middleware('role:supervisor');
    Route::post('/{user}/reject', 'Auth\ResetPasswordController@rejectResetRequest')->name('reject-request')->middleware('role:supervisor');
});

Route::middleware(['auth', 'role:superadmin'])->prefix('superadmins')->name('superadmins.')->group(function () {
    Route::get('/','IAM\IAMController@superadminIndex')->name('index');
});

//Company Routes

Route::middleware(['auth', 'role:superadmin|supervisor'])->prefix('companies')->name('companies.')->group(function () {
    Route::resource('/','Company\CompanyController')->parameters(['' => 'company']);
});

app/Models/Debt.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Debt extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function debitAccount(){
        return $this->belongsTo(Account::class, 'debit_account_id');
    }

    public function creditAccount(){
        return $this->belongsTo(Account::class, 'credit_account_id');
    }

    public function client(){
        return $this->belongsTo(Client::class, 'client_id');
    }

    public function cash(){
        return $this->belongsTo(Cash::class, 'cash_id');
    }
}

app/Http/Controllers/Debt/ClientController.php
<?php

namespace App\Http\Controllers\Debt;

use App\Exports\ClientReport;
use App\Exports\ClientsReport;
use App\Http\Controllers\Controller;
use App\Http\Requests\ClientStoreRequest;
use App\Http\Requests\ClientTypeStoreRequest;
use App\Http\Requests\ClientTypeUpdateRequest;
use App\Http\Requests\ClientUpdateRequest;
use App\Repositories\Debt\Client\ClientRepositoryInterface;
use App\Repositories\Debt\Client\ClientTypeRepositoryInterface;
use App\Services\ExportService;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    private ClientRepositoryInterface $clientRepository;
    private ClientTypeRepositoryInterface $clientTypeRepository;

    public function __construct(ClientRepositoryInterface $clientRepository, ClientTypeRepositoryInterface $clientTypeRepository)
    {
        $this->clientRepository = $clientRepository;
        $this->clientTypeRepository = $clientTypeRepository;
    }

    public function index(Request $request)
    {
        $clientTypes = $this->clientTypeRepository->getAllByRange($request);
        $clients = $this->clientRepository->getAllByRange($request);

        return view('debts.clients.index', compact('clients', 'clientTypes'));
    }

    public function create()
    {
        $clientTypes = $this->clientTypeRepository->getAll();

        return view('debts.clients.create', compact('clientTypes'));
    }

    public function store(ClientStoreRequest $request)
    {
        $this->clientRepository->create($request->validated());

        return redirect(route('debts.clients.index'));
    }

    public function show(Request $request, $id)
    {
        $client = $this->clientRepository->findByIdAndRange($id, $request);

        return view('debts.clients.show', compact('client'));
    }

    public function edit($id)
    {
        $client = $this->clientRepository->findById($id);
        $clientTypes = $this->clientTypeRepository->getAll();

        return view('debts.clients.edit', compact('client', 'clientTypes'));
    }

    public function update(ClientUpdateRequest $request, $id)
    {
        $this->clientRepository->update($id, $request->validated());

        return redirect(route('debts.clients.index'));
    }

    public function destroy($id)
    {
        $this->clientRepository->delete($id);

        return redirect(route('debts.clients.index'));
    }

    public function storeType(ClientTypeStoreRequest $request){
        $this->clientTypeRepository->create($request->validated());

        return redirect(route('debts.clients.create'));
    }

    public function updateType(ClientTypeUpdateRequest $request, $id){
        $this->clientTypeRepository->update($id, $request->validated());

        return redirect(route('debts.clients.index'));
    }

    public function clientExportExcel(Request $request, $id, ExportService $exportService){
        $client = $this->clientRepository->findByIdAndRange($id, $request);
        $clientCode = $client->code;
        $rangeDate = $exportService->setData($request)
            ->getRangeDateText();

        return (new ClientReport($client, $rangeDate))->download("Kartu_${clientCode}_${rangeDate}.xlsx");
    }

    public function clientsExportExcel(Request $request, ExportService $exportService){
        $clientTypes = $this->clientTypeRepository->getAllByRange($request);
        $clients = $this->clientRepository->getAllByRange($request);
        $rangeDate = $exportService->setData($request)
            ->getRangeDateText();

        return (new ClientsReport($clients, $clientTypes, $rangeDate))->download("Rekapitulasi Hutang_${rangeDate}.xlsx");
    }
}

app/Http/Controllers/Debt/DebtController.php
<?php

namespace App\Http\Controllers\Debt;

use App\Exports\DebtsReport;
use App\Http\Controllers\Controller;
use App\Http\Requests\DebtStoreRequest;
use App\Http\Requests\DebtUpdateRequest;
use App\Repositories\Account\AccountRepositoryInterface;
use App\Repositories\Debt\Client\ClientRepositoryInterface;
use App\Repositories\Debt\DebtRepositoryInterface;
use App\Services\ExportService;
use Illuminate\Http\Request;

class DebtController extends Controller
{
    private DebtRepositoryInterface $debtRepository;

    public function __construct(DebtRepositoryInterface $debtRepository)
    {
        $this->debtRepository = $debtRepository;
    }

    public function index(Request $request)
    {
        $debts = $this->debtRepository
            ->getAllByRange($request);

        return view('debts.journals.index', compact('debts'));
    }

    public function create(ClientRepositoryInterface $clientRepository, AccountRepositoryInterface $accountRepository)
    {
        $clients = $clientRepository->getAll();
        $accounts = $accountRepository->getAll();

        return view('debts.journals.create', compact('clients', 'accounts'));
    }

    public function store(DebtStoreRequest $request)
    {
        $this->debtRepository->create($request->validated());

        return redirect(route('debts.journals.index'));
    }

    public function edit($id, ClientRepositoryInterface $clientRepository, AccountRepositoryInterface $accountRepository)
    {
        $debt = $this->debtRepository->findById($id);
        $clients = $clientRepository->getAll();
        $accounts = $accountRepository->getAll();
        return view('debts.journals.edit', compact('debt', 'clients', 'accounts'));
    }

    public function update(DebtUpdateRequest $request, $id)
    {
        $this->debtRepository->update($id, $request->validated());

        return redirect(route('debts.journals.index'));
    }

    public function destroy($id)
    {
        $this->debtRepository->delete($id);

        return redirect(route('debts.journals.index'));
    }

    public function exportExcel(Request $request, ExportService $exportService){
        $debts = $this->debtRepository
            ->getAllByRange($request);
        $rangeDate = $exportService->setData($request)
            ->getRangeDateText();

        return (new DebtsReport($debts, $rangeDate))->download("Jurnal Hutang_${rangeDate}.xlsx");
    }
}

resources/views/debts/journals/create.blade.php
@extends('layouts.dashboard')

@section('dashboard-content')
    <div class="p-4">
        <!-- Page Heading -->
        <div class="mb-4 d-flex align-items-center justify-content-between">
            <h1 class="h3 text-primary font-weight-bold mb-0">Tambah Data Hutang</h1>
        </div>

        <div class="card shadow-sm">
            <form class="card-body" action="{{route('debts.journals.store')}}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <x-inputs.select
                            required
                            label="Supplier"
                            name="client"
                            placeholder="Pilih supplier"
                            search
                            :option-values="$clients->map(fn($client)=>$client->id)"
                            :option-names="$clients->map(fn($client)=>$client->name)"
                        />
                        <x-inputs.input
                            label="Tanggal"
                            name="date"
                            type="date"
                            :value="date('Y-m-d')"
                            required/>
                        <x-inputs.textarea
                            label="Uraian"
                            name="description"
                            rows="3"
                            placeholder="Masukkan uraian"/>
                        <x-inputs.input
                            label="No. Bukti"
                            name="invoice_num"
                            placeholder="Masukkan no. bukti"/>
                    </div>
                    <div class="col-md-6">
                        <div class="form-row">
                            <div class="form-group col-6">
                                <div class="custom-control custom-radio">
                                    <input type="radio" id="billType" name="type" class="custom-control-input" value="bill" checked>
                                    <label class="custom-control-label" for="billType">Tagihan</label>
                                </div>
                            </div>
                            <div class="form-group col-6">
                                <div class="custom-control custom-radio">
                                    <input type="radio" id="paymentType" name="type" class="custom-control-input" value="payment">
                                    <label class="custom-control-label" for="paymentType">Pembayaran</label>
                                </div>
                            </div>
                        </div>
                        <x-inputs.input
                            label="Nilai Tagihan"
                            name="bill_value"
                            id="billValue"
                            type="number"
                            step="0.001"
                            placeholder="Masukkan nilai tagihan"/>
                        <x-inputs.input
                            label="Nilai Pembayaran"
                            name="payment_value"
                            id="paymentValue"
                            type="number"
                            step="0.001"
                            disabled
                            placeholder="Masukkan nilai pembayaran"/>
                        <x-inputs.textarea
                            label="Keterangan"
                            name="information"
                            rows="3"
                            placeholder="Masukkan keterangan..."/>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-6">
                        <x-inputs.select
                            label="Akun Debit"
                            name="debit_account"
                            placeholder="Pilih akun"
                            search
                            :option-values="$accounts->map(fn($acc)=>$acc->id)"
                            :option-names="$accounts->map(fn($acc)=>$acc->account_num.' - '.$acc->name)"
                        />
                    </div>
                    <div class="col-md-6">
                        <x-inputs.select
                            label="Akun Kredit"
                            name="credit_account"
                            placeholder="Pilih akun"
                            search
                            :option-values="$accounts->map(fn($acc)=>$acc->id)"
                            :option-names="$accounts->map(fn($acc)=>$acc->account_num.' - '.$acc->name)"
                        />
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-12 text-right">
                        <a href="{{route('debts.journals.index')}}" class="btn btn-light mr-3">Batal</a>
                        <button class="btn btn-primary"><i class="fas fa-save"></i> Tambah Data Hutang</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready( function () {
            const typeChecks = $("input[name='type']");
            typeChecks.change(function(){
                if(this.checked){
                    updateTransactionInput($(this).val());
                }
            });

            function updateTransactionInput(type){
                if(type === 'bill'){
                    $('#billValue').prop('disabled', false);
                    $('#paymentValue').prop('disabled', true);
                } else if(type === 'payment') {
                    $('#billValue').prop('disabled', true);
                    $('#paymentValue').prop('disabled', false);
                }
            }
        } );
    </script>
@endpush

resources/views/debts/journals/index.blade.php
@extends('layouts.dashboard')

@section('dashboard-content')
    <div class="p-4">
        <!-- Page Heading -->
        <div class="mb-4 d-flex align-items-center justify-content-between">
            <h1 class="h3 text-primary font-weight-bold mb-0">Jurnal Hutang</h1>
        </div>

        <div class="mb-4 d-flex flex-column align-items-end flex-md-row justify-content-md-between align-items-md-center">
            <div class="align-self-start">
                <x-period-filter :route="route('debts.journals.index')" />
            </div>
            <div class="mt-3 mt-md-0 d-flex">
                <x-btn-export :route="route('debts.journals.index.export.excel')" class="mr-1"/>
                <a href="{{route('debts.journals.create')}}" class="btn btn-primary">
                    <i class="fas fa-plus"></i> Tambah Data Hutang
                </a>
            </div>
        </div>

        <div class="card shadow-sm">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover data-table" width="100%" cellspacing="0">
                        <thead>
                            <tr class="text-uppercase small text-primary">
                                <th>No.</th>
                                <th>Tanggal</th>
                                <th>Nama Supplier</th>
                                <th>Uraian</th>
                                <th>Tagihan</th>
                                <th>Pembayaran</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th class="text-right" colspan="4">Total</th>
                                <th class="text-right">Rp <span class="mask-money">{{$debts->reduce(fn($sum,$item)=>$sum+$item->bill_value)}}</span></th>
                                <th class="text-right">Rp <span class="mask-money">{{$debts->reduce(fn($sum,$item)=>$sum+$item->payment_value)}}</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach ($debts as $debt)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>
                                        {{(new Carbon\Carbon($debt->date))->format('d M Y')}}
                                    </td>
                                    <td>
                                        @if ($debt->client)
                                            {{$debt->client->name}} <br>
                                            <small class="text-gray-500">{{$debt->client->code}}</small>
                                        @else
                                            <div class="badge badge-danger rounded-pill px-2 py-1">Unknown</div>
                                        @endif
                                    </td>
                                    <td>{{$debt->description ?? '-'}}</td>
                                    <td class="text-right">Rp <span class="mask-money">{{$debt->bill_value ?? 0}}</span></td>
                                    <td class="text-right">Rp <span class="mask-money">{{$debt->payment_value ?? 0}}</span></td>
                                    <td class="text-center">
                                        @if($debt->is_complete)
                                            <div class="badge badge-success rounded-pill px-2 py-1">Complete</div>
                                        @else
                                            <div class="badge badge-danger rounded-pill px-2 py-1">Incomplete</div>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        <a href="" id="actionDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fas fa-ellipsis-v text-gray-500"></i>
                                        </a>
                                        <!-- Dropdown - User Information -->
                                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="actionDropdown">
                                            @if ($debt->client)
                                                <a class="dropdown-item" href="{{route('debts.clients.show', $debt->client->id)}}">
                                                    <i class="fas fa-eye fa-sm fa-fw mr-2 text-gray-400"></i>
                                                    Lihat Supplier
                                                </a>
                                            @endif
                                            <a class="dropdown-item" href="{{route('debts.journals.edit', $debt->id)}}">
                                                <i class="fas fa-edit fa-sm fa-fw mr-2 text-gray-400"></i>
                                                Sunting
                                            </a>
                                            <a class="dropdown-item delete" href="{{route('debts.journals.destroy', $debt->id)}}">
                                                <i class="fas fa-trash fa-sm fa-fw mr-2 text-gray-400"></i>
                                                Hapus
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function () {
            $('body').on('click', '.delete', function (event) {
                event.preventDefault();
                let action = $(this).attr('href');
                $('#deleteForm').attr('action', action);
                $('#deleteModal').modal('show');
            });
        });
    </script>
@endpush

@push('modals')
    <div>
        <!-- Delete Modal-->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <form id="deleteForm" class="modal-content" method="POST">
                    @csrf
                    @method('DELETE')
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Apakah Anda Yakin?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Data akan terhapus permanen jika anda menghapusnya.</div>
                    <div class="modal-footer">
                        <button class="btn btn-light" type="button" data-dismiss="modal">Batal</button>
                        <button type="submit" class="btn btn-danger">
                            <i class="fas fa-trash mr-1"></i>
                            Hapus
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <!-- End of Modal -->
    </div>
@endpush